// 算力网模型目录纯函数单测：归类 / Agent 适配 / 参数夹紧 / 计价（依据 suanli.com/api-docs）
import * as Sl from '../src/lib/suanli'
let pass = 0, fail = 0; const ok = (n: string, c: any, x = '') => { c ? pass++ : fail++; console.log(`${c ? '✅' : '❌'} ${n}${x ? '  ' + x : ''}`) }
const ids = Sl.BUILTIN.map((m) => m.id)
ok('内置 22 个模型（与模型广场一致）', ids.length === 22, String(ids.length))
ok('四大类齐全', ['chat', 'vision', 'image', 'video'].every((c) => Sl.BUILTIN.some((m) => m.cat === c)))
ok('视频 8 个：Seedance 6 + 文生 2', Sl.BUILTIN.filter((m) => m.cat === 'video').length === 8 && Sl.BUILTIN.filter((m) => m.proto === 'video_generic').length === 2)
ok('Seedance 支持四种素材角色', Sl.find('doubao-seedance-2-0-cmcc1')!.roles!.join() === 'first_frame,reference_image,reference_video,reference_audio')
ok('Seedance 2.5 分辨率只有 480p / 720p，时长 ≤30', (() => { const m = Sl.find('doubao-seedance-2-5-volc1')!; const r = m.params.find((p) => p.k === 'resolution')!, d = m.params.find((p) => p.k === 'duration')!; return r.options!.join() === '480p,720p' && d.max === 30 })())
ok('Seedance 2.0 时长 ≤15，含 1080p', (() => { const m = Sl.find('seedance2.0-qidian')!; return m.params.find((p) => p.k === 'duration')!.max === 15 && m.params.find((p) => p.k === 'resolution')!.options!.includes('1080p') })())
ok('主线视频拒绝纯文生模型（不能锁人物）', /reference_image/.test(Sl.fitFor('VIDEO_MAIN', Sl.find('wan2.7-t2v')) || ''))
ok('分支视频拒绝纯文生模型（不能首帧接力）', /first_frame/.test(Sl.fitFor('VIDEO_BRANCH', Sl.find('happyhorse-1.1-t2v')) || ''))
ok('一致性质检必须能看图', !!Sl.fitFor('CONSISTENCY', Sl.find('deepseek-v4-pro-0813')) && !Sl.fitFor('CONSISTENCY', Sl.find('doubao-seed-2-0-pro')))
ok('结构化 Agent 拒绝无 json_mode 模型', !!Sl.fitFor('SCRIPT', Sl.find('MiniMax-M3')) && !!Sl.fitFor('SCRIPT', Sl.find('qwen3.7-plus')))
ok('编剧不能选图片 / 视频模型', !!Sl.fitFor('SCREENWRITER', Sl.find('wan2.7-image')) && !!Sl.fitFor('SCREENWRITER', Sl.find('doubao-seedance-2-0-cmcc1')))
ok('设定图只能选图片模型', !Sl.fitFor('ASSET', Sl.find('wan2.7-image-pro')) && !!Sl.fitFor('ASSET', Sl.find('kimi-k3')))
ok('推荐模型均通过适配校验', Object.entries(Sl.NEEDS).every(([c, n]) => n.pick.every((id) => !Sl.fitFor(c, Sl.find(id)))))
let n = Sl.normalizeParams(Sl.find('doubao-seedance-2-5-volc1'), { resolution: '1080p', duration: 99, audio: 'true' })
ok('参数夹紧：2.5 传 1080p → 回默认 720p', n.params.resolution === '720p' && n.fixes.length === 2, JSON.stringify(n))
ok('参数夹紧：时长 99 → 30；布尔规范化', n.params.duration === 30 && n.params.audio === true)
n = Sl.normalizeParams(Sl.find('deepseek-v4-flash-0731'), { temperature: 5, reasoning_effort: 'ultra', custom_x: 1 })
ok('对话参数：温度 5 → 2、非法推理力度回默认、表外参数保留', n.params.temperature === 2 && n.params.reasoning_effort === '' && n.params.custom_x === 1)
ok('Seedance token/秒：720p = 21600（文档 5 秒 ≈ 108,900）', Sl.vtokPerSec('720p') === 21600)
ok('Seedance 2.0 720p ≈ ¥0.99/秒，1080p ≈ ¥2.48/秒', Sl.videoPerSec(Sl.find('doubao-seedance-2-0-cmcc1'), '720p') === 0.994 && Sl.videoPerSec(Sl.find('doubao-seedance-2-0-cmcc1'), '1080p') === 2.479)
ok('Seedance 2.5 720p ≈ ¥1.51/秒', Sl.videoPerSec(Sl.find('doubao-seedance-2-5-volc1'), '720p') === 1.512)
ok('万相文生 720p ¥0.6/秒', Sl.videoPerSec(Sl.find('wan2.7-t2v'), '720p') === 0.6)
ok('按上游 usage 计费：108900 token × ¥46/M = ¥5.009', Sl.costOf(Sl.find('doubao-seedance-2-0-cmcc1'), { vtok: 108900 }) === 5.009)
ok('对话计费：Flash 1M 入 + 1M 出 = ¥12', Sl.costOf(Sl.find('deepseek-v4-flash-0731'), { tin: 1e6, tout: 1e6 }) === 12)
ok('图片计费：Pro ¥0.5 / 张', Sl.costOf(Sl.find('wan2.7-image-pro'), { images: 1 }) === 0.5)
ok('通用协议尺寸：9:16 720p → 720x1280', Sl.sizeOf('9:16', '720p') === '720x1280' && Sl.sizeOf('16:9', '1080p') === '1920x1080')
console.log(`\n${pass} passed, ${fail} failed`); process.exit(fail ? 1 : 0)
