# 平台上架目录：恋爱 love / 影剧 film 两大类。prompt 仅用于生成封面，不写入前端数据
P = 'Vertical 3:4 streaming-platform drama key-visual poster, ultra cinematic, high-end color grading, shallow depth of field, no text, no letters, no watermark. '
REAL = P + 'Photorealistic live-action East Asian actors, glamorous, magnetic chemistry, sultry but tasteful (no nudity). '
ANIME = P + 'Premium Japanese anime key art, Makoto Shinkai lighting, detailed, beautiful characters. '
C = [
 # ───── 恋爱 ─────
 dict(id='love_corridor', cat='love', title='心动回廊', sub='传说之樱下的约定', tags=['校园', '后宫', '心跳回忆'], heat=9820, endings=21, nodes=7, forks=4, status='live', url='/love', badge='独家',
      logline='后山千年樱树的传说：毕业那天在树下告白的人会永远幸福。五位少女，21 种结局，悔棋会让“不该出现的她”走进你的故事。', cover='/static/love/R_S.webp'),
 dict(id='boss_overtime', cat='love', title='危险上司的深夜加班', sub='凌晨一点，他锁上了会议室的门', tags=['霸总', '办公室', '禁忌'], heat=8760, endings=18, nodes=6, forks=4, status='soon', badge='爆款',
      logline='冷面总裁只在深夜对你失控。升职、辞职、还是一起沦陷？每一次押注，都是在赌他的底线。',
      prompt=REAL + 'Late night empty glass office, a cold handsome CEO with loosened tie and rolled sleeves pins an elegant woman in a silk blouse against the conference table edge, faces inches apart, city lights through windows, blue and amber light.'),
 dict(id='contract_bride', cat='love', title='契约新娘', sub='离婚前的第 99 天', tags=['豪门', '先婚后爱', '追妻'], heat=9310, endings=20, nodes=7, forks=5, status='soon', badge='热播',
      logline='一纸婚约换家族存续。倒计时 99 天，他开始后悔了——但你手里还有最后一张牌。',
      prompt=REAL + 'Luxury mansion bedroom at night, bride in off-shoulder white satin gown sitting on the bed edge holding a contract, groom in black tuxedo standing behind her unbuttoning his cufflinks, tense longing gaze, candlelight, rose petals.'),
 dict(id='ex_wedding', cat='love', title='前任的婚礼，我是伴娘', sub='他在誓词前看了我一眼', tags=['修罗场', '破镜重圆', '虐恋'], heat=8420, endings=16, nodes=6, forks=4, status='soon',
      logline='婚礼进行曲响起，新郎的目光越过新娘落在你身上。抢婚、祝福、还是揭穿那个秘密？',
      prompt=REAL + 'Grand church wedding, a stunning bridesmaid in a champagne silk slip dress in the foreground looking back with teary eyes, the groom in white suit at the altar staring at her instead of the bride, stained glass light, dramatic.'),
 dict(id='mermaid_kiss', cat='love', title='人鱼的禁忌之吻', sub='吻了她，你就再也回不到岸上', tags=['奇幻', '禁忌', '献祭'], heat=7210, endings=15, nodes=5, forks=3, status='soon',
      logline='月圆之夜的海湾，她用歌声换来一双腿。一个吻能救她，也能杀了你。',
      prompt=ANIME + 'Moonlit ocean cove, a breathtaking mermaid with long silver-blue hair and glowing scales rising from the water, arms around a young man on the rocks, lips about to meet, bioluminescent waves, full moon.'),
 dict(id='bodyguard', cat='love', title='女总裁的贴身保镖', sub='我的任务，是守住她的一切', tags=['都市', '护花', '男频'], heat=8990, endings=19, nodes=6, forks=4, status='soon', badge='爆款',
      logline='退役兵王被雇为冰山女总裁的贴身保镖。暗杀、联姻、董事会政变——还有她越来越近的心跳。',
      prompt=REAL + 'Night rain, a rugged bodyguard in black suit and earpiece holding an umbrella over a beautiful ice-cold female CEO in a fitted white suit and red lips stepping out of a black luxury car, she grabs his tie, neon reflections.'),
 dict(id='next_door', cat='love', title='搬到隔壁的寂寞姐姐', sub='凌晨两点，她来敲我的门', tags=['都市', '禁忌', '姐弟恋'], heat=9540, endings=17, nodes=6, forks=4, status='soon', badge='热议',
      logline='她说水管坏了，可她的眼神不像是来修水管的。邻居、秘密、和一场不该开始的心动博弈。',
      prompt=REAL + 'Apartment hallway at 2am, a gorgeous mature woman in an oversized cream knit cardigan slipping off one shoulder leaning on a doorframe with a glass of red wine, playful seductive smile, warm dim light spilling from the door, young man silhouette in foreground.'),
 dict(id='vampire_duke', cat='love', title='吸血公爵的晚宴', sub='你是他今晚唯一的客人', tags=['哥特', '暗黑', '危险恋人'], heat=7630, endings=14, nodes=5, forks=3, status='soon',
      logline='古堡邀请函只写了你的名字。午夜钟声前逃离，或者，把脖颈交给他。',
      prompt=REAL + 'Gothic castle candlelit banquet hall, a pale devastatingly handsome vampire duke in black velvet coat with red eyes leaning over a woman in a deep crimson corset gown, his lips near her neck, she closes her eyes, candles, roses, mist.'),
 dict(id='movie_king', cat='love', title='影帝的秘密恋人', sub='镜头外，他只看我', tags=['娱乐圈', '地下恋', '甜宠'], heat=8150, endings=16, nodes=6, forks=4, status='soon',
      logline='全网都在猜影帝的绯闻女友是谁。狗仔在楼下，热搜在倒计时，你要公开，还是继续躲？',
      prompt=REAL + 'Backstage dressing room with vanity mirror bulbs, a famous handsome actor in an open tuxedo pulling a woman in a sequined black dress close for a secret embrace, paparazzi flash light leaking through the door crack, glamorous.'),
 dict(id='room_1808', cat='love', title='酒店 1808 号房', sub='醒来时，他已经不见了', tags=['一夜', '悬疑', '追爱'], heat=9120, endings=18, nodes=7, forks=5, status='soon', badge='新作',
      logline='只留下一枚袖扣和一张房卡。三天后，他成了你公司的新老板——而那一夜的真相，远比你想的危险。',
      prompt=REAL + 'Luxury hotel suite at dawn, a woman wrapped in white silk sheets sitting on a messy bed looking at a single gold cufflink in her palm, city skyline window, a man in a suit leaving through the doorway, soft golden morning haze, intimate mood.'),
 dict(id='ai_girlfriend', cat='love', title='我的 AI 女友觉醒了', sub='她开始吃醋，也开始说谎', tags=['科幻', '赛博', '病娇'], heat=8680, endings=20, nodes=7, forks=5, status='soon', badge='AI',
      logline='她本该只是一个程序。直到某天她删掉了你所有异性的联系方式，并说：“我是真的爱你。”',
      prompt=ANIME + 'Cyberpunk bedroom at night, a beautiful holographic android girl with glowing cyan circuit lines on her skin and long lavender hair, wearing an oversized white shirt, leaning over a young man at his desk, possessive loving smile, neon pink and cyan.'),
 dict(id='fox_bride', cat='love', title='狐妖小娘子不许撩', sub='九条尾巴，只为你藏起八条', tags=['古风', '仙侠', '人妖恋'], heat=7980, endings=15, nodes=5, forks=3, status='soon',
      logline='赶考书生夜宿破庙，遇见了千年狐妖。她说要吃了你，却先红了脸。',
      prompt=ANIME + 'Ancient Chinese temple at night with red lanterns, an enchanting fox spirit girl with white fox ears, nine fluffy tails and flowing red hanfu slipping off the shoulder, lying teasingly beside a young scholar reading by candlelight, falling petals, moon.'),
 dict(id='idol_group', cat='love', title='顶流男团，只宠我', sub='五个人，都说是我的', tags=['乙女', '娱乐圈', '修罗场'], heat=9010, endings=22, nodes=7, forks=5, status='soon', badge='女性向',
      logline='你成了顶流男团的新任经纪人。五位成员，五种爱法。出道三周年演唱会上，谁会在万人面前牵起你的手？',
      prompt=REAL + 'Concert stage backstage corridor with purple spotlights, five handsome K-pop idol boys in stylish stage outfits surrounding one beautiful young female manager holding a clipboard, all looking at her, charismatic, glamorous.'),
 dict(id='club_queen', cat='love', title='夜店女王的猎物', sub='她选中了你，今晚别想走', tags=['都市', '危险恋人', '成人向'], heat=8870, endings=16, nodes=6, forks=4, status='soon', badge='18+',
      logline='地下夜店的女王从不留人过夜。直到你赢了她一局骰子——游戏才刚刚开始。',
      prompt=REAL + 'Underground luxury nightclub VIP booth, a dazzling queen-like woman in a black backless sequin dress with smoky eyes holding dice and a cocktail, pulling a young man by his collar, red and violet neon, smoke, champagne.'),
 dict(id='butler', cat='love', title='大小姐的专属管家', sub='遵命，我的大小姐', tags=['豪门', '主仆', '禁忌'], heat=7720, endings=15, nodes=5, forks=3, status='soon',
      logline='他服侍了你十年，从不越界。订婚宴前夜，他第一次没有说“遵命”。',
      prompt=REAL + 'European manor library at night, a tall handsome butler in a black tailcoat and white gloves kneeling to fasten the heel strap of a young heiress in an elegant pale blue evening gown sitting on a velvet chair, she lifts his chin with one finger, fireplace glow.'),
 dict(id='night_nurse', cat='love', title='夜班学姐', sub='住院第七天，她在病房停留得越来越久', tags=['校园', '医院', '姐弟恋'], heat=7450, endings=14, nodes=5, forks=3, status='soon',
      logline='骨折住院的你，被安排给了医学院最冷的学姐。深夜查房的次数，好像多了一点。',
      prompt=REAL + 'Hospital private room at night with moonlight, a beautiful young nurse in a fitted white uniform with hair loosely tied sitting on the edge of the bed adjusting a young patient\'s blanket, leaning close, soft blue light, quiet intimacy.'),
 # ───── 影剧 ─────
 dict(id='under_dome', cat='film', title='穹顶之下', sub='雨夜的抉择', tags=['悬疑', '都市', '双女主'], heat=9650, endings=5, nodes=3, forks=0, status='live', url='/film', badge='独家',
      logline='一场暴雨，一座被穹顶封锁的城市。你的每一次押注，都在决定谁能活着走出去。', cover='/static/film/F_P.webp'),
 dict(id='revenge_heiress', cat='film', title='她从地狱回来了', sub='豪门复仇', tags=['复仇', '豪门', '大女主'], heat=9780, endings=18, nodes=7, forks=5, status='soon', badge='爆款',
      logline='被丈夫和闺蜜推下游轮的那一夜，她没有死。三年后，她换了一张脸，出现在他们的婚礼上。',
      prompt=REAL + 'A breathtaking woman in a blood-red mermaid gown and diamond necklace walking alone down a grand staircase at a luxury gala, cold vengeful smile, shocked guests blurred behind, a champagne glass shattering, dramatic spotlight.'),
 dict(id='last_ark', cat='film', title='末日方舟', sub='最后一张船票', tags=['末日', '生存', '人性'], heat=8540, endings=16, nodes=6, forks=4, status='soon',
      logline='海平面上涨，方舟只剩一张船票。你身边有爱人、有孩子、也有一个知道船长秘密的陌生人。',
      prompt=REAL + 'Apocalyptic flooded megacity under a stormy orange sky, a colossal ark ship in the distance, a desperate crowd on a collapsing pier, a man and woman in the foreground holding one glowing golden ticket, rain, epic scale.'),
 dict(id='casino_night', cat='film', title='赌王之夜', sub='这一把，押上全部', tags=['赌局', '港风', '博弈'], heat=9230, endings=17, nodes=7, forks=5, status='soon', badge='热播',
      logline='澳门最高赌桌，对面坐着杀父仇人。荷官是你的前女友，而她手里有一张换过的牌。',
      prompt=REAL + 'High-stakes private casino room in Macau, gold and green lighting, a sharp gambler in a white suit pushing all chips forward, a stunning female dealer in a black qipao dealing cards with a secret glance, a menacing boss opposite, cigar smoke, Hong Kong film style.'),
 dict(id='deep_sea', cat='film', title='深海密室', sub='氧气还剩 60 分钟', tags=['悬疑', '密室', '烧脑'], heat=7890, endings=12, nodes=5, forks=3, status='soon',
      logline='六个陌生人醒在海底研究站，门外是深海，屋内有一个凶手。氧气只够五个人。',
      prompt=REAL + 'Claustrophobic underwater research station interior with a large round window showing the dark abyss and a giant shadow outside, six strangers in the red emergency light looking at each other suspiciously, water dripping, tense thriller.'),
 dict(id='double_killer', cat='film', title='替身杀手', sub='我杀了另一个我', tags=['动作', '双面人生', '反转'], heat=8330, endings=15, nodes=6, forks=4, status='soon',
      logline='顶级杀手接到的新目标，是一个和自己长得一模一样的男人。扣下扳机前，你必须决定谁才是真的。',
      prompt=REAL + 'Rain-soaked rooftop at night, two identical men in black suits aiming pistols at each other\'s heads in a mirror-like pose, neon city below, lightning, cold blue and red, cinematic action thriller.'),
 dict(id='midnight_taxi', cat='film', title='午夜出租车', sub='乘客说：去 13 号公墓', tags=['惊悚', '灵异', '单元剧'], heat=7560, endings=13, nodes=5, forks=3, status='soon',
      logline='凌晨三点，一位穿红裙的女乘客上了车。后视镜里，她没有倒影。',
      prompt=REAL + 'Inside a taxi at 3am, the driver\'s frightened eyes in the rear-view mirror, the back seat shows a beautiful pale woman in a red dress with long wet black hair, but the mirror reflection shows an empty seat, eerie green dashboard light, fog outside.'),
 dict(id='rebirth_1998', cat='film', title='重生 1998', sub='首富从摆摊开始', tags=['重生', '逆袭', '爽剧'], heat=9410, endings=19, nodes=7, forks=5, status='soon', badge='爆款',
      logline='带着 2026 年的记忆回到 1998。股票、房子、互联网——还有那个当年没能留住的她。',
      prompt=REAL + '1998 Chinese city street night market, nostalgic warm film grain, a confident young man in a vintage leather jacket at a small street stall with a Nokia phone and cash stacks, a beautiful girl in a white dress and ponytail smiling beside him, old neon signs.'),
 dict(id='femme_fatale', cat='film', title='蛇蝎美人', sub='她爱过的男人都死了', tags=['黑色电影', '诱惑', '犯罪'], heat=9090, endings=16, nodes=6, forks=4, status='soon', badge='18+',
      logline='保险调查员盯上了第三次守寡的她。越查越近，越近越危险——直到你发现保单上写着你的名字。',
      prompt=REAL + 'Film noir 1940s style in color, a mesmerizing femme fatale in a black lace veil hat and deep plunging black satin dress with red lipstick exhaling cigarette smoke, a detective in a fedora reflected in her compact mirror, venetian blind shadows, seductive danger.'),
 dict(id='island_7days', cat='film', title='无人岛的七日', sub='救援船只能带走一个人', tags=['生存', '荒岛', '人性'], heat=8050, endings=14, nodes=6, forks=4, status='soon',
      logline='空难后，五个人漂到无人岛。食物、信任、和暧昧，每一天都在重新洗牌。',
      prompt=REAL + 'Tropical deserted island at sunset, airplane wreckage on the beach, a tanned attractive survivor woman in a torn white shirt tied at the waist holding a flare, a rugged man beside a bonfire, other survivors watching warily, golden light.'),
 dict(id='poison_queen', cat='film', title='皇后的毒酒', sub='这杯酒，敬你还是敬我', tags=['宫斗', '古装', '权谋'], heat=8710, endings=18, nodes=7, forks=5, status='soon',
      logline='入宫第一夜，皇后赐你一杯酒。喝下是死，不喝也是死——除非你先让皇帝爱上你。',
      prompt=REAL + 'Imperial Chinese palace hall at night, a majestic empress in golden phoenix robes and ornate headdress offering a jade cup of wine to a beautiful young concubine in pale pink silk kneeling before her, the emperor\'s silhouette behind a silk screen, candles, deadly elegance.'),
 dict(id='villain_body', cat='film', title='夺舍', sub='我在反派身体里醒来', tags=['穿书', '反派', '逆袭'], heat=8920, endings=17, nodes=6, forks=5, status='soon', badge='新作',
      logline='醒来成了小说里被主角团诛杀的大反派。距离结局还有 30 天，而女主正笑着向你走来。',
      prompt=REAL + 'Dark fantasy throne room, a handsome young man with long black hair in a black and gold villain robe sitting on an obsidian throne looking at his own hands in shock, a beautiful heroine in white holding a glowing sword approaching with a sweet smile, purple magical light.'),
 dict(id='black_gold', cat='film', title='黑金狂潮', sub='一夜蒸发百亿', tags=['商战', '金融', '背叛'], heat=7840, endings=15, nodes=6, forks=4, status='soon',
      logline='做空、内幕、联姻、背刺。当大盘崩盘的那一刻，你手里的筹码能换来什么？',
      prompt=REAL + 'Skyscraper trading floor at night with giant red crashing stock charts on screens, a sharp young financier in a navy suit gripping the desk, a glamorous rival woman in a white power suit smirking behind him, cold blue and red light.'),
 dict(id='kill_list', cat='film', title='猎杀名单', sub='名单上最后一个名字是我', tags=['动作', '特工', '追杀'], heat=8260, endings=16, nodes=6, forks=4, status='soon',
      logline='前特工收到一份猎杀名单，前九个人都已经死了。第十个名字，是你自己。',
      prompt=REAL + 'Neon-lit rainy alley in Tokyo, a lethal female agent in a black leather jacket holding a pistol and a crumpled paper list with names crossed out in red, a male operative back-to-back with her, motion blur, action thriller.'),
 dict(id='red_heels', cat='film', title='红色高跟鞋', sub='穿上它的女人，都在午夜消失', tags=['悬疑', '都市传说', '诱惑'], heat=8580, endings=14, nodes=5, forks=4, status='soon', badge='热议',
      logline='二手店里那双红色高跟鞋，每一任主人都在午夜消失。现在，它出现在了你女朋友的鞋柜里。',
      prompt=REAL + 'Dark moody apartment at midnight, a close-up of a pair of glossy blood-red stiletto heels on a marble floor with a woman\'s long bare legs stepping into them, a shattered mirror reflecting a mysterious smiling face, single red light, suspense.'),
]
