# 《喵总裁今天也在裁员》导演精修剧本（抽象剧 · 喵语翻译局玩法）→ POST /api/director/brief (outline 模式)
import json, sys, urllib.request as U
S = lambda desc, speaker='', line='', sfx='': dict(desc=desc, speaker=speaker, line=line, sfx=sfx)
M, L, Z, X = 'MaoZong', 'LiWei', 'ZhaoYan', 'XiaoMing'
outline = dict(
 title='喵总裁今天也在裁员',
 cast=[
  dict(id=M, name='喵总', side='R', role='刚收购公司的橘猫 CEO，只会说“喵”，每一声都决定谁被裁',
       look='a chubby orange tabby cat with round amber eyes, wearing a tiny tailored black suit, white shirt and a shiny gold tie, sits upright like a human boss'),
  dict(id=L, name='李伟', side='L', role='嘴碎老油条打工人，全公司最会吐槽的人',
       look='a tired young Chinese office man, messy short black hair, dark eye bags, wrinkled light-blue shirt with loosened red tie, blue company lanyard'),
  dict(id=Z, name='赵燕', side='L', role='PPT 女王项目经理，一本正经地“同声传译”喵语',
       look='a sharp young Chinese woman project manager, neat black bob haircut, thin gold glasses, fitted charcoal blazer and pencil skirt, holding a tablet'),
  dict(id=X, name='小明', side='L', role='天然呆实习生，坚信自己听得懂猫语',
       look='a cheerful chubby Chinese intern boy, bowl haircut, oversized yellow hoodie with a paw-print sticker, big round glasses'),
 ],
 setting='A symmetrical pastel-candy corporate boardroom built like a claymation stop-motion set (Wes Anderson framing): long mint-green table, pink walls, giant KPI chart on a projector screen, fish-shaped pendant lamps, a huge brown leather CEO chair at the head of the table. Everything is handmade clay with visible fingerprint texture.',
 mech=dict(type='meow', name='喵语翻译局', rule='喵总每叫一声，你押哪一种“翻译”是对的'),
 q1='喵总：『喵～？』（尾音上扬，盯着全体）——这声喵到底什么意思？',
 prologue=dict(title='周一早会，老板是只猫', meme='新老板到岗，全员起立',
  shots=[S('Wide symmetrical shot of the boardroom, clay office workers stand up in shock as the door opens, spotlight falls on the giant CEO chair', sfx='door creak, dramatic orchestral sting'),
         S(f'The orange cat {M} in a tiny suit hops onto the CEO chair and slaps a paw on a stack of layoff notices, camera slowly pushes in', M, '喵～？', 'paw slap on paper'),
         S(f'Close-up of {Z} adjusting her glasses, reading her tablet very seriously like a UN interpreter', Z, '喵总说：本季度要降本增效。', 'tablet beep'),
         S(f'{L} leans to {X}, whispering with a deadpan face while {X} nods excitedly', L, '降本？降的是我们吧？', 'nervous gulp')]),
 routes=[
  dict(label='要小鱼干', hint='赵燕：它饿了，先喂老板', title='全员献鱼干', meme='全员跪献小鱼干',
   shots=[S('Symmetrical shot: all clay employees kneel in a row, raising bags of dried fish over their heads toward the cat like an offering ceremony', sfx='choir aah'),
          S(f'{L} pushes a gift box with a red bow onto the table, forcing a huge fake smile', L, '喵总，这是我三个月的绩效。', 'box slide'),
          S(f'The cat {M} sniffs the dried fish slowly, eyes half closed, tension music', M, '喵……', 'sniff sniff'),
          S(f'{Z} holds up a pie chart made of dried fish slices', Z, '鱼干投入产出比，已对齐颗粒度。', 'ding')],
   endings=[
    dict(label='够了，全员留下', hint='李伟：稳了稳了', title='首席鱼干官', tone='love', meme='李伟升任首席鱼干官',
     shots=[S(f'The cat {M} happily chews a dried fish and stamps a paw print on a promotion letter', M, '喵～！', 'happy chewing, stamp'),
            S(f'{L} receives a golden fish-shaped name badge that reads nothing, confetti falls', L, '我，首席鱼干官，上任了。', 'confetti pop'),
            S('Everyone cheers and throws dried fish in the air in slow motion, candy colors', sfx='cheering crowd')]),
    dict(label='不够，再加三斤', hint='赵燕：它在谈价', title='鱼干通货膨胀', tone='risk', meme='鱼干涨到比工资还贵',
     shots=[S(f'The cat {M} pushes the fish away and holds up three claws', M, '喵！喵！喵！', 'three sharp meows'),
            S(f'{Z} shows a projector chart: dried fish price curve rocketing upward like a stock chart', Z, '鱼干价格，已经超过工资了。', 'alarm beep'),
            S(f'{L} drags a giant sack of dried fish in, sweating, the room fills up with fish to the ceiling', L, '这哪是上班，这是进货。', 'sack thud')]),
    dict(label='它其实吃素', hint='小明：我早就说了', title='喵总吃素', tone='twist', twist=True, meme='献鱼的全被裁了',
     shots=[S(f'Plot twist: the cat {M} pushes all fish off the table, then pulls out a tiny green salad bowl', M, '喵。', 'record scratch'),
            S(f'{X} proudly presents a pot of cat grass, glowing with holy light', X, '我带的是猫草！', 'heavenly choir'),
            S(f'Layoff notices rain down on everyone holding fish, only {X} is left smiling alone at the table', sfx='paper rain')]),
   ]),
  dict(label='要你们学猫', hint='小明：它想要同类', title='全员学猫开会', meme='全公司跪地学猫叫开会',
   shots=[S('Top-down symmetrical shot: the whole team crawls on the conference table on all fours, wearing paper cat ears', sfx='awkward meows'),
          S(f'{Z} presents a slide deck while licking her hand like a cat, totally serious', Z, '喵，本季度，喵，增长百分之三。', 'slide click'),
          S(f'{L} curls up inside a cardboard box on the table, deadpan', L, '我在工位上待了十年，终于有纸箱了。', 'cardboard rustle'),
          S(f'The cat {M} stares at them with judging narrowed eyes', M, '喵喵喵！', 'three quick meows')],
   endings=[
    dict(label='学得太像，全留', hint='小明：我们被认可了', title='全员猫化办公', tone='love', meme='周报用爪印签名',
     shots=[S(f'The cat {M} purrs and gives everyone a paw stamp on their weekly reports', M, '喵～呼噜噜', 'purring'),
            S('Montage: employees nap on keyboards, chase a laser dot, knock cups off desks, all in clay', sfx='cup falling, laughter'),
            S(f'{L} yawns on a cat tower next to the window', L, '这是我上过最舒服的班。', 'yawn')]),
    dict(label='太假了，全裁', hint='赵燕：它嫌我们演技差', title='爪印盖章', tone='betrayal', meme='裁员通知书盖了个爪印',
     shots=[S(f'The cat {M} hisses and stomps a big paw print stamp on every layoff notice, one by one, rhythmically', M, '嘶——喵！', 'stamp stamp stamp'),
            S(f'{Z} still in cat ears, holding the notice, calmly', Z, '我们被猫嫌弃了，这很专业。', ''),
            S(f'{L} walks out carrying his cardboard box, which he is still sitting inside', L, '箱子我带走了。', 'door close')]),
    dict(label='它想学人类', hint='李伟：反向操作？', title='喵总去打卡', tone='twist', twist=True, meme='老板自己去打卡上班了',
     shots=[S(f'Twist: the cat {M} stands up on two legs, puts on a human employee lanyard and walks to the time clock', M, '喵。', 'clock-in beep'),
            S(f'The cat sits at a tiny desk typing on a keyboard furiously, working overtime under a single lamp', sfx='keyboard clatter'),
            S(f'{L} and {X} now sit in the giant CEO chair together, confused', L, '所以……现在我们是老板？', 'dramatic sting')]),
   ]),
  dict(label='要裁掉一半', hint='李伟：受够了，罢工！', title='李伟发动罢工', meme='拒绝画饼，从我做起',
   shots=[S(f'{L} jumps onto the table holding a handmade cardboard protest sign, employees behind him hold signs too', L, '拒绝画饼！拒绝九九六！', 'crowd chanting'),
          S(f'{Z} tears a slide titled with a giant pie drawing into pieces', Z, '这张饼，我画了三年。', 'paper tearing'),
          S(f'{X} bangs a spoon on a cat food can like a drum', sfx='can drumming'),
          S(f'The cat {M} slams its paw on the table, fur standing up', M, '喵！', 'loud paw slam')],
   endings=[
    dict(label='准了，改双休', hint='赵燕：它被打动了', title='喵式作息', tone='love', meme='公司改成一天睡十六小时',
     shots=[S(f'The cat {M} nods and draws a new schedule on the whiteboard: a giant sleeping moon covering the whole day', M, '喵～', 'marker squeak'),
            S(f'{Z} reads aloud from her tablet in disbelief', Z, '新制度：每天睡十六个小时。', ''),
            S('Everyone falls asleep instantly on the table in a symmetrical row, soft lullaby', sfx='snoring, lullaby')]),
    dict(label='你被开了', hint='小明：伟哥保重', title='逗猫棒送客', tone='sacrifice', meme='被逗猫棒赶出公司',
     shots=[S(f'The cat {M} pulls out a feather teaser wand and points it at {L} like a sword', M, '喵。', 'sword unsheath'),
            S(f'{L} is chased out of the door by a giant bouncing feather wand, running in slow motion', L, '我还有年假没休啊！', 'running footsteps'),
            S(f'{X} waves goodbye with a paw-shaped glove, tears in eyes', X, '伟哥，我会替你摸鱼的。', 'sad violin')]),
    dict(label='它也要罢工', hint='李伟：老板加入了？', title='老板带头罢工', tone='twist', twist=True, meme='老板带头罢工：拒绝洗澡',
     shots=[S(f'Twist: the cat {M} jumps down and joins the protest line, holding a tiny sign with a bathtub crossed out', M, '喵！喵！', 'crowd gasps'),
            S(f'{Z} translates while marching', Z, '喵总的诉求：拒绝洗澡，猫粮自由。', 'marching drum'),
            S(f'{L} shakes the cat paw like two union leaders on a stage, flash photography', L, '同志，原来你也是打工猫。', 'camera flashes')]),
   ]),
 ],
 q2=['喵总：『喵……』（长音，眯眼）——它对鱼干满意吗？', '喵总：『喵喵喵！』（急促三连）——它怎么评价你们的猫叫？', '喵总：『喵！』（拍桌短促一声）——罢工的下场是？'],
 hidden_route=dict(label='它只是饿了', hint='悔棋才会出现', title='小明开罐头', meme='一个罐头拯救了全公司',
   shots=[S(f'{X} secretly opens a can of cat food under the table, the pop sound echoes in the silent boardroom', X, '喵总，开饭了。', 'can pop, echo'),
          S(f'The cat {M} instantly turns its head 180 degrees, eyes huge and sparkling', M, '喵？！', 'sparkle sound'),
          S(f'{Z} and {L} look at each other in disbelief, then at the pile of dried fish', L, '早说啊，我们演了半天。', 'awkward silence')]),
 fork=dict(title='裂隙：喵总是被遥控的', meme='老板是被遥控的？',
   question='时间裂隙：遥控器在你手上，你要按哪个键？',
   shots=[S('Glitch effect, time rewinds with VHS distortion, the room freezes in pastel colors', sfx='rewind glitch'),
          S(f'{L} crawls under the table and finds a pink game controller with a cat face and big buttons', L, '等等，老板是被遥控的？', 'mysterious chime'),
          S(f'{X} looks away guilty, whistling, his phone screen shows a cat app', X, '那个……是我的喵总模拟器。', 'whistle'),
          S(f'Close-up of {L} thumb hovering over two big buttons, dramatic zoom', sfx='heartbeat')],
   endings=[
    dict(label='按「全员加薪」', hint='李伟：人生巅峰', title='我遥控了老板', meme='按一下，全员加薪',
     shots=[S(f'{L} presses the button, the cat {M} robotically raises a paw and meows in a synthetic voice', M, '喵。加薪。', 'robot beep'),
            S('Money made of clay rains down from the fish lamps, everyone dances', sfx='coins raining, party music'),
            S(f'{L} holds the controller like a king, grinning', L, '原来当老板这么简单。', 'triumphant fanfare')]),
    dict(label='按「关机」', hint='小明：别按！', title='原来它只是困了', meme='老板没被遥控，它只是困了',
     shots=[S(f'{L} presses power off, the cat {M} yawns hugely and curls up to sleep on the layoff notices', M, '喵……呼噜', 'yawn, purring'),
            S(f'{X} shows his phone: the app was never connected, a big clay X mark', X, '其实我一直没连上。', 'error buzz'),
            S(f'Everyone tiptoes out quietly so as not to wake the boss, soft lullaby, symmetrical wide shot', sfx='tiptoe, lullaby')]),
    dict(label='遥控器在遥控我', hint='悔棋才会出现', title='我才是被遥控的', twist=True, meme='原来被遥控的是我',
     shots=[S(f'{L} presses a button but HE starts meowing and walking on all fours, while the cat {M} holds a second controller and smirks', L, '喵？！等等，怎么是我？', 'glitch buzz'),
            S(f'The camera pulls back: {Z} and {X} also move like puppets, strings of clay yarn above them lead to the cat paw', Z, '原来我们一直都是被遥控的。', 'eerie music box'),
            S(f'The cat {M} leans back in the CEO chair, drinking milk from a wine glass', M, '喵～', 'glass clink')]),
   ]),
 bonus=dict(
  gold=dict(title='👑 黄金彩蛋·喵总年会独舞', meme='喵总年会独舞，全场沸腾',
   shots=[S('Annual party: the boardroom transforms into a disco with a mirror ball made of dried fish', sfx='disco music'),
          S(f'The cat {M} in a sparkly gold suit dances on the table under spotlights, doing a moonwalk', M, '喵～喵～喵～', 'disco beat'),
          S(f'{L}, {Z} and {X} wave glow sticks screaming like fans', L, '老板！再来一个！', 'crowd screaming')]),
  platinum=dict(title='🏆 白金彩蛋·真正的老板', meme='老板的老板是一只更大的猫',
   shots=[S('The projector screen flickers and a video call opens', sfx='video call ringtone'),
          S(f'On the screen: a gigantic lion in a tailored suit with a gold tie sitting in a skyscraper office, the orange cat {M} bows nervously', M, '喵……', 'nervous meow'),
          S(f'{Z} translates with a trembling voice', Z, '这是集团董事长，它说：全员降薪。', 'thunder'),
          S(f'{L} faints backwards onto the table in slow motion', L, '猫上有猫啊！', 'body thud')]),
  diamond=dict(title='💎 钻石彩蛋·全公司变成猫', meme='李伟成了新的喵总',
   shots=[S('Magical glitter swirl fills the boardroom, every employee slowly transforms into a cute clay cat wearing their office clothes', sfx='magic chime'),
          S(f'{Z} as a black cat with gold glasses still holding the tablet', Z, '喵，喵喵，喵。', ''),
          S(f'{L} as a grey tabby cat in a loose red tie sits in the giant CEO chair, the orange cat {M} hands him the gold tie', M, '喵。', 'crown fanfare'),
          S(f'{L} the cat stares into the camera with a deadpan face', L, '喵。（翻译：明天全员放假）', 'epic orchestral hit')]),
 ),
)
meta = dict(item_id='abs_cat_ceo', cat='abstract', genre='absurd', scale='standard', auto=True, title='喵总裁今天也在裁员',
            theme='周一早会，公司被一只橘猫收购了。它只会说“喵”，但每一声都决定谁被裁——押对喵语翻译，你就能活下来。',
            outline=outline, mech=outline['mech'])
if __name__ == '__main__':
    base = sys.argv[1] if len(sys.argv) > 1 else 'http://localhost:3000'
    r = U.urlopen(U.Request(base + '/api/director/brief', data=json.dumps(meta, ensure_ascii=False).encode(), headers={'content-type': 'application/json'}), timeout=60)
    print(r.read().decode())
